language: node_js
#  latest stable Node.js release
node_js: node
# Cache node packages between jobs
cache: npm
branches:
  only:
    - master
    - production
jobs:
  include:
    - # require the branch name to be master
      if: branch = master
      env:
        - FIREBASE_PROJECT=staging
        - SENTRY_ENVIRONMENT=staging
        # firebase
        - FIREBASE_API_KEY=AIzaSyDG_OMeMaXVIHJqZpTzkY_DAWV9ylNwlXM,
        - FIREBASE_AUTH_DOMAIN=staging-pocketpasta.firebaseapp.com,
        - FIREBASE_DATABASE_URL=https://staging-pocketpasta.firebaseio.com,
        - FIREBASE_PROJECT_ID=staging-pocketpasta,
        - FIREBASE_STORAGE_BUCKET=staging-pocketpasta.appspot.com,
        - FIREBASE_MESSAGING_SENDER_ID=216453269763,
        - FIREBASE_APP_ID=1:216453269763:web:71a3fe1ca24500bb,

    - # require the branch name to be production
      if: branch = production
      env:
        - FIREBASE_PROJECT=default
        - SENTRY_ENVIRONMENT=production
        # firebase
        - FIREBASE_API_KEY=AIzaSyB-2aw2OIfQzirEE6tv4YTWLMEuG6aWpbk,
        - FIREBASE_AUTH_DOMAIN=pocketpasta-46ac6.firebaseapp.com,
        - FIREBASE_DATABASE_URL=https://pocketpasta-46ac6.firebaseio.com,
        - FIREBASE_PROJECT_ID=pocketpasta-46ac6,
        - FIREBASE_STORAGE_BUCKET=pocketpasta-46ac6.appspot.com,
        - FIREBASE_MESSAGING_SENDER_ID=904516376213,
        - FIREBASE_APP_ID=1:904516376213:web:b2f6a99e9607f076,

script:
  - npm run lint
  - npm run test
  - npm run generate:modern
  # Propose release version
  - VERSION=$(./node_modules/.bin/sentry-cli releases propose-version)
  # Create a release
  - ./node_modules/.bin/sentry-cli releases new -p pocketpasta $VERSION
  # Associate commits with the release
  - ./node_modules/.bin/sentry-cli releases set-commits "$VERSION" --auto

before_deploy:
  - npx semantic-release
  - npm run generate:modern
deploy:
  # Keep dist folder for deploy
  skip_cleanup: true
  provider: firebase
  project: $FIREBASE_PROJECT
  token:
    secure: L/UAkAWLM/+GPflHbpFh3cPa7475WgMVd9BFKeWo89dquWyMLbFaLFaxHxYXLcWcIgUMCVe5y1g1qbPpRChDb0kHUU5ATFMUNQBiWDsjOZq8FjrtW1rNgIWpo/so1iykQGhamALoOUiqsZkKuemDknRPEjI7IZqCaflHyPhkuDmSPqA+bqFOfd+eP4GOTA9gMLbTrV7oVs6kWYv0KwlPdW/B2blzLddfYBGcU+xphffDxkMgerqP4t+IHp44T4qKsvOBBNksqEiCc5DYSSh4OWiNSeC/SzRiVFGEvz1cA0clMbtT1pNgW5E3j2lGMuzFm3Wc7sBjNQuX9CYVsy8RcEzqJ+4g6cdVhVFYxRZD11/b8SlgieBs7YrGU60ByoyAB1XqLal+cZBARtqorEzs6JLVTHEcVd4zYa9ge5GvbD736Pg/2OuL272meZo2RW4clPatoLXb1DIHljij0SVI9ry7i8oCl+s0sgPm+MSvRXFvSL9pWGFJ4LjKcTGQzQEDk2Vkb9OZgJ6acT5sjfb7Rroj0XeyM7Y9lgTOD6b9JytpLe3jCEA0EXHy4HB6rRoT+JvA8DUmWuI17/ya5K9a5PMn699GeaUc2QK/7R+wNhovJof9E+fyXtBsufMm+62J6wCn42+o7G4jbPeX0DIf9mQ4XDixpSmrmgj/UjgDbY8=
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|production$
after_deploy:
  - ./node_modules/.bin/sentry-cli releases deploys "$VERSION" new --env $SENTRY_ENVIRONMENT

env:
  global:
    # FIREBASE_AUTH_TOKEN
    - secure: L/UAkAWLM/+GPflHbpFh3cPa7475WgMVd9BFKeWo89dquWyMLbFaLFaxHxYXLcWcIgUMCVe5y1g1qbPpRChDb0kHUU5ATFMUNQBiWDsjOZq8FjrtW1rNgIWpo/so1iykQGhamALoOUiqsZkKuemDknRPEjI7IZqCaflHyPhkuDmSPqA+bqFOfd+eP4GOTA9gMLbTrV7oVs6kWYv0KwlPdW/B2blzLddfYBGcU+xphffDxkMgerqP4t+IHp44T4qKsvOBBNksqEiCc5DYSSh4OWiNSeC/SzRiVFGEvz1cA0clMbtT1pNgW5E3j2lGMuzFm3Wc7sBjNQuX9CYVsy8RcEzqJ+4g6cdVhVFYxRZD11/b8SlgieBs7YrGU60ByoyAB1XqLal+cZBARtqorEzs6JLVTHEcVd4zYa9ge5GvbD736Pg/2OuL272meZo2RW4clPatoLXb1DIHljij0SVI9ry7i8oCl+s0sgPm+MSvRXFvSL9pWGFJ4LjKcTGQzQEDk2Vkb9OZgJ6acT5sjfb7Rroj0XeyM7Y9lgTOD6b9JytpLe3jCEA0EXHy4HB6rRoT+JvA8DUmWuI17/ya5K9a5PMn699GeaUc2QK/7R+wNhovJof9E+fyXtBsufMm+62J6wCn42+o7G4jbPeX0DIf9mQ4XDixpSmrmgj/UjgDbY8=
    # SENTRY_AUTH_TOKEN
    - secure: TVTycyjJi+EOzbteaZUsk7zyIScxb9mCpy0hq2JqPNh6PZakgW36KclPGUKRwEFvmR5AN68RkLA9qAVIDQOEyqa6Rlc8OtL+8X3GWt1aV7h5O0X7r6G8WVOFrBA88m1jRIvVo/GuhEzzy6xp2LYfxDOvQ58PfrX5nQQXh0VjLF6RgFWF9tRqRyv4MUAWXA4Ulf1ZlJ7hLJOq4B27EIRobqYEt3hWNrzndJ+CWopbvhORMZlnBO2hvDZnTs1T4Ezhj4rgPw1ljHv3g2pVQhKJ182pwzE3F6jcSmz/q/I6oOT6ow1DvXE93DRP47XymC1dmXxeHHONg/WRZfpiCAqm1MXZH1uzdAFUcqHKU3v2oq98gZmvjkYwQUsnBiMSFwWYyG9ZwvGEbvVnWg0zzAR6BVaxfSBwyM+9gkUJH5JW5GCt80AVmg1G9WtVuj4LQzskMk32lQObHIHwWK5wA8HgZQk0E3h+kJACEvkb5Fm6jDBmW77Wo57vTEF8YMzCGmmpRxGHf1EGkikVOu2VF6xasnHE4dw00+yNUNbfD4/oiEOpgC2ILTuP/XzTlEZHAOHAnMtg6lqoizTUbFiIiw2B+Mg4g+olhxN+nrEcQHHUV5yKlceGyYIiJcnMO/AfD5WKfwNzPQTPt35XH4iPLigPFMx2b5t7j6SfOXSh6bmQ2q8=
    # PERCY_TOKEN
    - secure: M+A8ISnwOzaw+KeTTyPSlzBFS2eywDSGBUh0LoudNeVWJEl0Pql4PrQCYq2KlYAXF+fgLhmt44djA9zZP8X+fRU5V81x+63FSDm0pWDiiWzaacEb2nVLn1eaaNK6eqmTvWI27nS37O9vPWSMhcv+nxrIkvrxKNvhAhuD1SPUCv9ZIJj7fT0xia50pk8+/itMe/MMqBgm3W4FwSvKvSG+VBMLB+NX9A6TTthFuIPAdk3CE9SeWTcRDLnybwIiDtMuojwCUiTac9Sg9FmuyPHZupf2o6x6j9LxzxjJZ3lrD3nFhTM8g5nup77aMaykmOGwnZLqszW8A7Y105WdXK8oOsqi9Jt6zErUpkjc+kBf5s0nEZW0RD4uMJP2PP1TvWz8lcwZHwGWcx1C3d6Twvf6JvIAi4EyvNzL4yaoM4gCa7jLgRTgASgGRpvz3JtjxosS6irZUQ4TErfYtD57ZEUWjAJh1GgIC2y4CLCgn5nWlr8gXUtH5Hro/kk71+eHnCc6gjU3OiHA217J7zCXt1GRqKa+hr/NtKbDdI1oy4WQ/Gq9dS6cK0q7KzkxMXexgpLo9BUgt6MDewdDdYc3YVQCm6DP/i3GfHF8CWNNTvgwW2tklkJta7s5t+bWWL2I5QegEJVVTjSWH1vmVO0JPvZcAC1amj/oQse1rRRedT7C/Hg=
    - SENTRY_ORG=pocketpasta
    - SENTRY_PROJECT=pocketpasta

notifications:
  email:
    recipients:
      - damien.robinson@pocketpasta.com
